### ISSUE TITLE
SVG import.

### ISSUE THREAD

**Issue by devogon** [opieters/business-card#1]
First I want to say nice work!

Second, having ensured all packages are installed on my system, the front builds perfectly, but building the back (with xelatex) gives an error about not finding the logo. I've used this on the github source and get the same failure. How do you import the logo.svg?

**Comment by jacobmischka** [comment]
I'm pretty sure that the author has a `logo.pdf` in `src/figures`, which is being ignored by the gitignore. 

LaTeX can't include svgs, and the `svg` latex package even just shells out to inkscape and converts it to a pdf on the fly. I imagine that's what the author did initially, and then just didn't realize it was being ignored.

**Comment by devogon** [comment]
inkscape --file=logo.svg --without-gui --export-area-drawing --export-pdf=logo.pdf

also does the trick

**Comment by opieters** [comment]
Indeed. I mention how to convert an SVG logo to PDF in the README. The PDF-logo is included now.
