### ISSUE TITLE
Font Awesome not found

### ISSUE THREAD

**Issue by chrisfinazzo** [opieters/business-card#4]
After forking and making some changes, I cannot get my card to compile. The following error appears which makes me think that there is a `.sty` file that should be included:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "FontAwesome" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.45 \newfontfamily{\FA}{FontAwesome}
```

The consensus here is that the [file][] doesn't need to be in the same directory and that normally TeX will do the right thing. However, because I am using BasicTex, is it possible that not everything I need is included?

[file]: https://tex.stackexchange.com/questions/399624/fontawesome-sty-36file-fontawesomesymbols-generic-tex-not-found

If I explicitly include a copy of the file, the error referenced in the title of that issue results and my code still produces an error.

[file]: https://tex.stackexchange.com/questions/399624/fontawesome-sty-36file-fontawesomesymbols-generic-tex-not-found

**Comment by AdrianKoshka** [comment]
do you have the [`fontawesome`](https://ctan.org/tex-archive/fonts/fontawesome?lang=en) package installed?

[front.tex](https://github.com/opieters/business-card/blob/master/src/front.tex#L12)

**Comment by chrisfinazzo** [comment]
I don't - hence the question of procedure. If it's as simple as downloading a few `.tex` and `.sty` files and throwing them in my project directory, I would appreciate the CTAN URLs.

As my BasicTex installation comes from Homebrew Cask, I admittedIy have less knowledge about the structure that TeX creates and how to manipulate it with `ctan install foo` or `tlmgr`. At present, I am just using it to typeset my CV.

Apologies submitted for my ignorance on this topic.

**Comment by AdrianKoshka** [comment]
I did link to CTAN page in my first response. Sadly I know nothing about TeX on macOS.
