### ISSUE TITLE
Unreadable QR code

### ISSUE THREAD

**Issue by polyluxus** [opieters/business-card#6]
I recently tried to include a vcard, too, and found your example. I basically ran into the same problem described here: [Problem creating a proper qrcode with vcard info](https://tex.stackexchange.com/q/212730/33413). When running your examples, I saw that this is also the case here:
https://github.com/opieters/business-card/blob/8f0c03b28b00abacea1b7439d925e039e3aebb72/src/back.tex#L52-L66

I suggest you also switch to:
```
\qrcode[level=M,height=\qrheight]{BEGIN:VCARD\?VERSION:3.0\?N:John;Doe;;Mr.\? <more> \?END:VCARD}
```

**Comment by opieters** [comment]
I will test this in the coming days (reproducibility of the problem and fix).

Just for reference: which compiler did you use? Since I compiled it with XeLaTeX 3 years ago and it worked then.

**Comment by polyluxus** [comment]
I have used pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019) for building the qr-code. I just tried xetex, which does indeed work fine. So I guess this does not apply to your repository then. 

I honestly do not know where the issue is, I cannot reproduce the problem anymore, and I don't know where I have the files that produced the garbage, so I can't investigate. Sorry to have bothered you.

**Comment by opieters** [comment]
Great! It works, that's the most important conclusion.
